-- =====================================================================
-- 酒店管理系统 Oracle 数据库 DDL 脚本
-- 共 12 张业务表 + 配套序列 + 索引 + 字典与管理员初始数据
-- 执行前提：使用任一拥有建表权限的 Oracle 用户登录后整体执行
-- =====================================================================

-- ---------- 清理旧对象（首次执行时会有 ORA-00942/02289，忽略即可） ----------
BEGIN
    BEGIN EXECUTE IMMEDIATE 'DROP FUNCTION F_NOW'; EXCEPTION WHEN OTHERS THEN NULL; END;
    FOR rec IN (SELECT table_name FROM user_tables WHERE table_name IN (
        'BILL_ITEM','CHECK_IN_RECORD','RESERVATION','HOTEL_ORDER',
        'ROOM_SERVICE','ROOM','ROOM_TYPE','GUEST_RECORD','CUSTOMER',
        'SYS_DICT','SYS_USER','SYS_ROLE','SYS_CLOCK'))
    LOOP
        EXECUTE IMMEDIATE 'DROP TABLE ' || rec.table_name || ' CASCADE CONSTRAINTS PURGE';
    END LOOP;
    FOR rec IN (SELECT sequence_name FROM user_sequences WHERE sequence_name LIKE 'SEQ_%')
    LOOP
        EXECUTE IMMEDIATE 'DROP SEQUENCE ' || rec.sequence_name;
    END LOOP;
END;
/

-- ============================== 模块零：虚拟时钟 ================================
-- 单行表存储相对真实时间的偏移天数；F_NOW() 返回 SYSDATE + OFFSET_DAYS。
-- 所有业务表的 CREATE_TIME / UPDATE_TIME / RECORD_TIME 默认值都用 F_NOW()。
CREATE TABLE SYS_CLOCK (
    ID           NUMBER(1)     PRIMARY KEY,
    OFFSET_DAYS  NUMBER(10,4)  DEFAULT 0 NOT NULL
);
COMMENT ON TABLE SYS_CLOCK IS '虚拟时钟（仅 1 行，ID=1）';
INSERT INTO SYS_CLOCK(ID, OFFSET_DAYS) VALUES (1, 0);

CREATE OR REPLACE FUNCTION F_NOW RETURN DATE IS
    v_off NUMBER;
BEGIN
    SELECT OFFSET_DAYS INTO v_off FROM SYS_CLOCK WHERE ID = 1;
    RETURN SYSDATE + v_off;
EXCEPTION
    WHEN NO_DATA_FOUND THEN RETURN SYSDATE;
END;
/

-- ============================== 模块一：系统与权限 ==============================
CREATE TABLE SYS_ROLE (
    ROLE_ID      NUMBER(10)    PRIMARY KEY,
    ROLE_NAME    VARCHAR2(50)  NOT NULL,
    DESCRIPTION  VARCHAR2(200),
    PERMISSIONS  VARCHAR2(2000),
    IS_DELETED   NUMBER(1)     DEFAULT 0,
    CREATE_TIME  DATE          DEFAULT SYSDATE,
    UPDATE_TIME  DATE          DEFAULT SYSDATE,
    UPDATE_BY    NUMBER(10)
);
COMMENT ON TABLE SYS_ROLE IS '系统角色表';
COMMENT ON COLUMN SYS_ROLE.PERMISSIONS IS '权限码 CSV，如 customer:view,bill:add';

CREATE TABLE SYS_USER (
    USER_ID      NUMBER(10)    PRIMARY KEY,
    USERNAME     VARCHAR2(50)  NOT NULL UNIQUE,
    PASSWORD     VARCHAR2(100) NOT NULL,
    REAL_NAME    VARCHAR2(50)  NOT NULL,
    ROLE_ID      NUMBER(10),
    STATUS       NUMBER(1)     DEFAULT 1,
    IS_DELETED   NUMBER(1)     DEFAULT 0,
    CREATE_TIME  DATE          DEFAULT SYSDATE,
    UPDATE_TIME  DATE          DEFAULT SYSDATE,
    UPDATE_BY    NUMBER(10),
    CONSTRAINT FK_USER_ROLE FOREIGN KEY (ROLE_ID) REFERENCES SYS_ROLE(ROLE_ID)
);
COMMENT ON TABLE SYS_USER IS '系统用户表';

CREATE TABLE SYS_DICT (
    DICT_ID      NUMBER(10)    PRIMARY KEY,
    TYPE_CODE    VARCHAR2(50)  NOT NULL,
    ITEM_VALUE   NUMBER(2)     NOT NULL,
    ITEM_NAME    VARCHAR2(50)  NOT NULL,
    SORT_ORDER   NUMBER(3)     DEFAULT 0,
    CREATE_TIME  DATE          DEFAULT SYSDATE,
    UPDATE_TIME  DATE          DEFAULT SYSDATE,
    UPDATE_BY    NUMBER(10)
);
COMMENT ON TABLE SYS_DICT IS '数据字典表';
CREATE UNIQUE INDEX UK_DICT_TYPE_VALUE ON SYS_DICT(TYPE_CODE, ITEM_VALUE);

-- ============================== 模块二：客户档案 ================================
CREATE TABLE CUSTOMER (
    CUSTOMER_ID  NUMBER(10)    PRIMARY KEY,
    CUST_NAME    VARCHAR2(50)  NOT NULL,
    ID_CARD      VARCHAR2(18)  NOT NULL UNIQUE,
    PHONE        VARCHAR2(20)  NOT NULL,
    GENDER       NUMBER(1),
    VIP_LEVEL    NUMBER(2)     DEFAULT 0,
    IS_DELETED   NUMBER(1)     DEFAULT 0,
    CREATE_TIME  DATE          DEFAULT SYSDATE,
    UPDATE_TIME  DATE          DEFAULT SYSDATE,
    UPDATE_BY    NUMBER(10)
);
COMMENT ON TABLE CUSTOMER IS '客户档案表';
CREATE INDEX IDX_CUSTOMER_NAME  ON CUSTOMER(CUST_NAME);
CREATE INDEX IDX_CUSTOMER_PHONE ON CUSTOMER(PHONE);

-- ============================== 模块三：客房 ====================================
CREATE TABLE ROOM_TYPE (
    TYPE_ID      NUMBER(10)    PRIMARY KEY,
    TYPE_NAME    VARCHAR2(50)  NOT NULL,
    BASE_PRICE   NUMBER(10,2)  NOT NULL,
    BED_COUNT    NUMBER(2),
    IS_DELETED   NUMBER(1)     DEFAULT 0,
    VERSION      NUMBER(10)    DEFAULT 0,
    CREATE_TIME  DATE          DEFAULT SYSDATE,
    UPDATE_TIME  DATE          DEFAULT SYSDATE,
    UPDATE_BY    NUMBER(10)
);
COMMENT ON TABLE ROOM_TYPE IS '客房类型表';

CREATE TABLE ROOM (
    ROOM_ID      NUMBER(10)    PRIMARY KEY,
    ROOM_NO      VARCHAR2(20)  NOT NULL UNIQUE,
    TYPE_ID      NUMBER(10)    NOT NULL,
    FLOOR_NUM    NUMBER(3),
    STATUS       NUMBER(2)     DEFAULT 1,
    IMAGE        BLOB,
    IMAGE_TYPE   VARCHAR2(50),
    IMAGE_NAME   VARCHAR2(200),
    IS_DELETED   NUMBER(1)     DEFAULT 0,
    VERSION      NUMBER(10)    DEFAULT 0,
    CREATE_TIME  DATE          DEFAULT SYSDATE,
    UPDATE_TIME  DATE          DEFAULT SYSDATE,
    UPDATE_BY    NUMBER(10),
    CONSTRAINT FK_ROOM_TYPE FOREIGN KEY (TYPE_ID) REFERENCES ROOM_TYPE(TYPE_ID)
);
COMMENT ON TABLE ROOM IS '客房物理表';
COMMENT ON COLUMN ROOM.IMAGE      IS '房间封面图（≤5MB，jpg/png/webp/gif）';
COMMENT ON COLUMN ROOM.IMAGE_TYPE IS '图片 MIME 类型，例如 image/jpeg';
COMMENT ON COLUMN ROOM.IMAGE_NAME IS '原始文件名（可选，仅供展示）';
CREATE INDEX IDX_ROOM_TYPE_STATUS ON ROOM(TYPE_ID, STATUS);

CREATE TABLE ROOM_SERVICE (
    SERVICE_ID   NUMBER(10)    PRIMARY KEY,
    ROOM_ID      NUMBER(10)    NOT NULL,
    SERVICE_TYPE NUMBER(2)     NOT NULL,
    REASON       VARCHAR2(200),
    STATUS       NUMBER(2)     DEFAULT 1,
    OPERATOR_ID  NUMBER(10),
    FINISH_TIME  DATE,
    CREATE_TIME  DATE          DEFAULT SYSDATE,
    UPDATE_TIME  DATE          DEFAULT SYSDATE,
    UPDATE_BY    NUMBER(10),
    CONSTRAINT FK_SERVICE_ROOM FOREIGN KEY (ROOM_ID)     REFERENCES ROOM(ROOM_ID),
    CONSTRAINT FK_SERVICE_USER FOREIGN KEY (OPERATOR_ID) REFERENCES SYS_USER(USER_ID)
);
COMMENT ON TABLE ROOM_SERVICE IS '客务与维修工单表';

-- ============================== 模块四：订单流转 ================================
CREATE TABLE HOTEL_ORDER (
    ORDER_ID     NUMBER(10)    PRIMARY KEY,
    ORDER_NO     VARCHAR2(50)  NOT NULL UNIQUE,
    CUSTOMER_ID  NUMBER(10)    NOT NULL,
    TOTAL_AMOUNT NUMBER(10,2)  DEFAULT 0,
    STATUS       NUMBER(2)     DEFAULT 1,
    IS_DELETED   NUMBER(1)     DEFAULT 0,
    VERSION      NUMBER(10)    DEFAULT 0,
    CREATE_TIME  DATE          DEFAULT SYSDATE,
    UPDATE_TIME  DATE          DEFAULT SYSDATE,
    UPDATE_BY    NUMBER(10),
    CONSTRAINT FK_ORDER_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
);
COMMENT ON TABLE HOTEL_ORDER IS '酒店总订单表';
CREATE INDEX IDX_ORDER_CREATE_TIME ON HOTEL_ORDER(CREATE_TIME);

CREATE TABLE RESERVATION (
    RES_ID       NUMBER(10)    PRIMARY KEY,
    ORDER_ID     NUMBER(10)    NOT NULL,
    TYPE_ID      NUMBER(10)    NOT NULL,
    EXPECT_IN    DATE          NOT NULL,
    EXPECT_OUT   DATE          NOT NULL,
    RES_STATUS   NUMBER(2)     DEFAULT 1,
    VERSION      NUMBER(10)    DEFAULT 0,
    CREATE_TIME  DATE          DEFAULT SYSDATE,
    UPDATE_TIME  DATE          DEFAULT SYSDATE,
    UPDATE_BY    NUMBER(10),
    CONSTRAINT FK_RES_ORDER FOREIGN KEY (ORDER_ID) REFERENCES HOTEL_ORDER(ORDER_ID),
    CONSTRAINT FK_RES_TYPE  FOREIGN KEY (TYPE_ID)  REFERENCES ROOM_TYPE(TYPE_ID)
);
COMMENT ON TABLE RESERVATION IS '预订明细表';

CREATE TABLE CHECK_IN_RECORD (
    RECORD_ID    NUMBER(10)    PRIMARY KEY,
    ORDER_ID     NUMBER(10)    NOT NULL,
    RES_ID       NUMBER(10),
    ROOM_ID      NUMBER(10)    NOT NULL,
    CHECK_IN     DATE          NOT NULL,
    CHECK_OUT    DATE,
    STATUS       NUMBER(2)     DEFAULT 1,
    VERSION      NUMBER(10)    DEFAULT 0,
    CREATE_TIME  DATE          DEFAULT SYSDATE,
    UPDATE_TIME  DATE          DEFAULT SYSDATE,
    UPDATE_BY    NUMBER(10),
    CONSTRAINT FK_CHECK_ORDER FOREIGN KEY (ORDER_ID) REFERENCES HOTEL_ORDER(ORDER_ID),
    CONSTRAINT FK_CHECK_RES   FOREIGN KEY (RES_ID)   REFERENCES RESERVATION(RES_ID),
    CONSTRAINT FK_CHECK_ROOM  FOREIGN KEY (ROOM_ID)  REFERENCES ROOM(ROOM_ID)
);
COMMENT ON TABLE CHECK_IN_RECORD IS '入住记录表';

CREATE TABLE GUEST_RECORD (
    GUEST_ID     NUMBER(10)    PRIMARY KEY,
    RECORD_ID    NUMBER(10)    NOT NULL,
    GUEST_NAME   VARCHAR2(50)  NOT NULL,
    ID_CARD      VARCHAR2(18)  NOT NULL,
    CREATE_TIME  DATE          DEFAULT SYSDATE,
    UPDATE_TIME  DATE          DEFAULT SYSDATE,
    UPDATE_BY    NUMBER(10),
    CONSTRAINT FK_GUEST_RECORD FOREIGN KEY (RECORD_ID) REFERENCES CHECK_IN_RECORD(RECORD_ID)
);
COMMENT ON TABLE GUEST_RECORD IS '同住人登记表';

-- ============================== 模块五：财务 ====================================
CREATE TABLE BILL_ITEM (
    ITEM_ID      NUMBER(10)    PRIMARY KEY,
    ORDER_ID     NUMBER(10)    NOT NULL,
    SEGMENT_ID   NUMBER(10),
    ITEM_TYPE    NUMBER(2)     NOT NULL,
    AMOUNT       NUMBER(10,2)  NOT NULL,
    REMARK       VARCHAR2(200),
    OPERATOR_ID  NUMBER(10),
    IS_DELETED   NUMBER(1)     DEFAULT 0,
    RECORD_TIME  DATE          DEFAULT SYSDATE,
    CONSTRAINT FK_BILL_ORDER   FOREIGN KEY (ORDER_ID)    REFERENCES HOTEL_ORDER(ORDER_ID),
    CONSTRAINT FK_BILL_USER    FOREIGN KEY (OPERATOR_ID) REFERENCES SYS_USER(USER_ID),
    CONSTRAINT FK_BILL_SEGMENT FOREIGN KEY (SEGMENT_ID)  REFERENCES CHECK_IN_RECORD(RECORD_ID)
);
COMMENT ON TABLE BILL_ITEM IS '财务账单明细表';
COMMENT ON COLUMN BILL_ITEM.SEGMENT_ID IS '关联入住段（仅房费时使用，用于按房型归账）';
CREATE INDEX IDX_BILL_RECORD_TIME ON BILL_ITEM(RECORD_TIME);

-- ============================== 序列 ===========================================
CREATE SEQUENCE SEQ_SYS_ROLE      START WITH 100 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_SYS_USER      START WITH 100 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_SYS_DICT      START WITH 100 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CUSTOMER      START WITH 100 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_GUEST_RECORD  START WITH 100 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_ROOM_TYPE     START WITH 100 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_ROOM          START WITH 100 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_ROOM_SERVICE  START WITH 100 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_HOTEL_ORDER   START WITH 100 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_RESERVATION   START WITH 100 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CHECK_IN      START WITH 100 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_BILL_ITEM     START WITH 100 INCREMENT BY 1 NOCACHE;

-- ============================== 初始化数据 =====================================

-- 角色（PERMISSIONS 用 CSV 存权限码；管理员置 *，登录后端按"含 * 即全权"处理）
INSERT INTO SYS_ROLE(ROLE_ID, ROLE_NAME, DESCRIPTION, PERMISSIONS) VALUES
    (1, '管理员',   '系统管理员，拥有所有权限', '*');
INSERT INTO SYS_ROLE(ROLE_ID, ROLE_NAME, DESCRIPTION, PERMISSIONS) VALUES
    (2, '普通前台', '前台日常运营，办理预订、入住、结算',
     'dashboard:view,customer:view,customer:edit,roomtype:view,room:view,reservation:view,reservation:edit,reservation:cancel,checkin:view,checkin:checkin,checkin:checkout,checkin:changeroom,order:view,order:cancel,bill:view,bill:add,housekeeping:view,housekeeping:dispatch,housekeeping:finish');
INSERT INTO SYS_ROLE(ROLE_ID, ROLE_NAME, DESCRIPTION, PERMISSIONS) VALUES
    (3, '财务',     '财务对账、报表统计、导出',
     'dashboard:view,customer:view,roomtype:view,room:view,reservation:view,checkin:view,order:view,order:settle,order:export,bill:view,bill:add,bill:delete,bill:shift,report:view,report:export');

-- 默认管理员（密码：admin123，已使用 SHA-256 加盐 hash 存储；盐固定为 'hotel'）
-- 注意：实际登录通过后端 PasswordUtil 进行校验，这里写死同一种 hash
INSERT INTO SYS_USER(USER_ID, USERNAME, PASSWORD, REAL_NAME, ROLE_ID, STATUS)
VALUES (1, 'admin',     '109f83e5f7a7866ba6624689fccf6bc5eeba58bd0173a0272067987c9d230ad7', '系统管理员', 1, 1);
INSERT INTO SYS_USER(USER_ID, USERNAME, PASSWORD, REAL_NAME, ROLE_ID, STATUS)
VALUES (2, 'reception', '109f83e5f7a7866ba6624689fccf6bc5eeba58bd0173a0272067987c9d230ad7', '前台小张', 2, 1);
INSERT INTO SYS_USER(USER_ID, USERNAME, PASSWORD, REAL_NAME, ROLE_ID, STATUS)
VALUES (3, 'finance',   '109f83e5f7a7866ba6624689fccf6bc5eeba58bd0173a0272067987c9d230ad7', '财务小李', 3, 1);

-- 字典：房态
INSERT INTO SYS_DICT(DICT_ID, TYPE_CODE, ITEM_VALUE, ITEM_NAME, SORT_ORDER) VALUES (1,  'ROOM_STATUS', 1, '空闲净房',  1);
INSERT INTO SYS_DICT(DICT_ID, TYPE_CODE, ITEM_VALUE, ITEM_NAME, SORT_ORDER) VALUES (3,  'ROOM_STATUS', 3, '已入住',    3);
INSERT INTO SYS_DICT(DICT_ID, TYPE_CODE, ITEM_VALUE, ITEM_NAME, SORT_ORDER) VALUES (4,  'ROOM_STATUS', 4, '空闲脏房',  4);
INSERT INTO SYS_DICT(DICT_ID, TYPE_CODE, ITEM_VALUE, ITEM_NAME, SORT_ORDER) VALUES (5,  'ROOM_STATUS', 5, '维修中',    5);

-- 字典：订单状态
INSERT INTO SYS_DICT(DICT_ID, TYPE_CODE, ITEM_VALUE, ITEM_NAME, SORT_ORDER) VALUES (10, 'ORDER_STATUS', 1, '进行中',    1);
INSERT INTO SYS_DICT(DICT_ID, TYPE_CODE, ITEM_VALUE, ITEM_NAME, SORT_ORDER) VALUES (11, 'ORDER_STATUS', 2, '已结算',    2);
INSERT INTO SYS_DICT(DICT_ID, TYPE_CODE, ITEM_VALUE, ITEM_NAME, SORT_ORDER) VALUES (12, 'ORDER_STATUS', 3, '已取消',    3);

-- 字典：预订状态
INSERT INTO SYS_DICT(DICT_ID, TYPE_CODE, ITEM_VALUE, ITEM_NAME, SORT_ORDER) VALUES (20, 'RES_STATUS', 1, '已预订',  1);
INSERT INTO SYS_DICT(DICT_ID, TYPE_CODE, ITEM_VALUE, ITEM_NAME, SORT_ORDER) VALUES (21, 'RES_STATUS', 2, '已入住',  2);
INSERT INTO SYS_DICT(DICT_ID, TYPE_CODE, ITEM_VALUE, ITEM_NAME, SORT_ORDER) VALUES (22, 'RES_STATUS', 3, '已取消',  3);
INSERT INTO SYS_DICT(DICT_ID, TYPE_CODE, ITEM_VALUE, ITEM_NAME, SORT_ORDER) VALUES (23, 'RES_STATUS', 4, '已爽约',  4);

-- 字典：入住状态
INSERT INTO SYS_DICT(DICT_ID, TYPE_CODE, ITEM_VALUE, ITEM_NAME, SORT_ORDER) VALUES (30, 'CHECK_STATUS', 1, '在住', 1);
INSERT INTO SYS_DICT(DICT_ID, TYPE_CODE, ITEM_VALUE, ITEM_NAME, SORT_ORDER) VALUES (31, 'CHECK_STATUS', 2, '已退', 2);

-- 字典：账单类型
INSERT INTO SYS_DICT(DICT_ID, TYPE_CODE, ITEM_VALUE, ITEM_NAME, SORT_ORDER) VALUES (40, 'BILL_TYPE', 1, '房费',     1);
INSERT INTO SYS_DICT(DICT_ID, TYPE_CODE, ITEM_VALUE, ITEM_NAME, SORT_ORDER) VALUES (41, 'BILL_TYPE', 2, '押金',     2);
INSERT INTO SYS_DICT(DICT_ID, TYPE_CODE, ITEM_VALUE, ITEM_NAME, SORT_ORDER) VALUES (42, 'BILL_TYPE', 3, '退押金',   3);
INSERT INTO SYS_DICT(DICT_ID, TYPE_CODE, ITEM_VALUE, ITEM_NAME, SORT_ORDER) VALUES (43, 'BILL_TYPE', 4, '违约金',   4);
INSERT INTO SYS_DICT(DICT_ID, TYPE_CODE, ITEM_VALUE, ITEM_NAME, SORT_ORDER) VALUES (44, 'BILL_TYPE', 5, '赔偿金',   5);
INSERT INTO SYS_DICT(DICT_ID, TYPE_CODE, ITEM_VALUE, ITEM_NAME, SORT_ORDER) VALUES (45, 'BILL_TYPE', 6, '其他',     6);

-- 字典：服务工单类型
INSERT INTO SYS_DICT(DICT_ID, TYPE_CODE, ITEM_VALUE, ITEM_NAME, SORT_ORDER) VALUES (50, 'SERVICE_TYPE', 1, '清扫',  1);
INSERT INTO SYS_DICT(DICT_ID, TYPE_CODE, ITEM_VALUE, ITEM_NAME, SORT_ORDER) VALUES (51, 'SERVICE_TYPE', 2, '维修',  2);

-- 字典：服务工单状态
INSERT INTO SYS_DICT(DICT_ID, TYPE_CODE, ITEM_VALUE, ITEM_NAME, SORT_ORDER) VALUES (60, 'SERVICE_STATUS', 1, '待处理', 1);
INSERT INTO SYS_DICT(DICT_ID, TYPE_CODE, ITEM_VALUE, ITEM_NAME, SORT_ORDER) VALUES (61, 'SERVICE_STATUS', 2, '处理中', 2);
INSERT INTO SYS_DICT(DICT_ID, TYPE_CODE, ITEM_VALUE, ITEM_NAME, SORT_ORDER) VALUES (62, 'SERVICE_STATUS', 3, '已完成', 3);

-- 房型样例
INSERT INTO ROOM_TYPE(TYPE_ID, TYPE_NAME, BASE_PRICE, BED_COUNT) VALUES (1, '标准大床房', 388.00, 1);
INSERT INTO ROOM_TYPE(TYPE_ID, TYPE_NAME, BASE_PRICE, BED_COUNT) VALUES (2, '标准双床房', 428.00, 2);
INSERT INTO ROOM_TYPE(TYPE_ID, TYPE_NAME, BASE_PRICE, BED_COUNT) VALUES (3, '豪华套房',   888.00, 1);
INSERT INTO ROOM_TYPE(TYPE_ID, TYPE_NAME, BASE_PRICE, BED_COUNT) VALUES (4, '行政套房',  1288.00, 1);

-- 客房样例
INSERT INTO ROOM(ROOM_ID, ROOM_NO, TYPE_ID, FLOOR_NUM, STATUS) VALUES (1, '801', 1, 8, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_NO, TYPE_ID, FLOOR_NUM, STATUS) VALUES (2, '802', 1, 8, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_NO, TYPE_ID, FLOOR_NUM, STATUS) VALUES (3, '803', 2, 8, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_NO, TYPE_ID, FLOOR_NUM, STATUS) VALUES (4, '901', 2, 9, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_NO, TYPE_ID, FLOOR_NUM, STATUS) VALUES (5, '902', 3, 9, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_NO, TYPE_ID, FLOOR_NUM, STATUS) VALUES (6, '1001', 3, 10, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_NO, TYPE_ID, FLOOR_NUM, STATUS) VALUES (7, '1801', 4, 18, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_NO, TYPE_ID, FLOOR_NUM, STATUS) VALUES (8, '1802', 4, 18, 1);

-- 客户样例
INSERT INTO CUSTOMER(CUSTOMER_ID, CUST_NAME, ID_CARD, PHONE, GENDER, VIP_LEVEL)
VALUES (1, '张三', '110101199001011234', '13800000001', 1, 0);
INSERT INTO CUSTOMER(CUSTOMER_ID, CUST_NAME, ID_CARD, PHONE, GENDER, VIP_LEVEL)
VALUES (2, '李四', '110101199203034567', '13800000002', 1, 1);
INSERT INTO CUSTOMER(CUSTOMER_ID, CUST_NAME, ID_CARD, PHONE, GENDER, VIP_LEVEL)
VALUES (3, '王梅', '110101199506067890', '13800000003', 2, 2);

COMMIT;
